spring:
  profiles:
    active:
    - dev
    
---

server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://192.168.140.128:3306/cloudDB01    #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
 

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.wzj.springcloud.entities #所有Entity别名类所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mqpper映射文件

  
eureka:
  client: #客户端注册进eureka服务列表中
    service-url:
      #defaultZone: http://localhost:7001/eureka  #eureka服务地址
      defaultZone: http://eureka7001.com:7001/eureka/  #eureka服务地址
  instance:
    instance-id: dept-8001.com  #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址

info: #配置info信息链接
  app.name: wzj-microservicecloud-springcloudconfig01
  company.name: www.wzj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


    
    
---

server:
  port: 8001
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://192.168.140.128:3306/cloudDB01    #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
 

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.wzj.springcloud.entities #所有Entity别名类所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mqpper映射文件

  
eureka:
  client: #客户端注册进eureka服务列表中
    service-url:
      #defaultZone: http://localhost:7001/eureka  #eureka服务地址
      defaultZone: http://eureka7001.com:7001/eureka/  #eureka服务地址
  instance:
    instance-id: dept-8001.com  #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址

info: #配置info信息链接
  app.name: wzj-microservicecloud-springcloudconfig01
  company.name: www.wzj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


#保存为utf-8格式
  